package com.mrivanplays.annotationconfig.core;

import com.mrivanplays.annotationconfig.core.annotations.Key;
import com.mrivanplays.annotationconfig.core.annotations.comment.Comment;

@Comment("Test subject config. Can change at any time")
@Comment("Generated by AnnotationConfig")
public class PropertiesTestSubject {

  @Comment("The message that will be sent to the player")
  @Comment("Bla bla 2nd comment")
  private String message = "this is a message";

  @Comment("The message sending strategy with which the message will be sent")
  @Key("message.type")
  private MessageType messageType = MessageType.STRING;

  public String getMessage() {
    return message;
  }

  public MessageType getMessageType() {
    return messageType;
  }

  public enum MessageType {
    COMPONENT,
    STRING
  }
}
