package com.mrivanplays.annotationconfig.core;

import java.lang.reflect.Field;

@Comment("Test subject config. Can change at any time")
@Comment("Generated by AnnotationConfig")
public class PropertiesTestSubject {

  @Comment("The message that will be sent to the player")
  @Comment("Bla bla 2nd comment")
  private String message = "this is a message";

  @Comment("The message sending strategy with which the message will be sent")
  @Key("message.type")
  @TypeResolver(MessageTypeResolver.class)
  private MessageType messageType = MessageType.STRING;

  public String getMessage() {
    return message;
  }

  public MessageType getMessageType() {
    return messageType;
  }

  public enum MessageType {
    COMPONENT,
    STRING
  }

  public static class MessageTypeResolver implements FieldTypeResolver {

    @Override
    public Object toType(Object value, Field field) throws Exception {
      if (value == null) {
        return null;
      }
      String sValue = String.valueOf(value);
      try {
        return MessageType.valueOf(sValue.toUpperCase());
      } catch (IllegalArgumentException e) {
        return null;
      }
    }

    @Override
    public boolean shouldResolve(Class<?> fieldType) {
      return MessageType.class.isAssignableFrom(fieldType);
    }
  }
}
