package com.mrivanplays.annotationconfig.yaml;

import com.mrivanplays.annotationconfig.core.annotations.ConfigObject;
import com.mrivanplays.annotationconfig.core.annotations.Key;
import com.mrivanplays.annotationconfig.core.annotations.comment.Comment;
import java.util.Arrays;
import java.util.List;

// the difference between YAMLTestSubject and this is that here we have some new options
// the new options need to show if generation of non-existing fields in the config work as intended.
@Comment("Generated by AnnotationConfig v2.0.0")
public class YAMLSecondTestSubject {

  @Comment("name")
  @Key("custom-name")
  private String name = "Ivan";

  @Comment("foo")
  private String foo = "bar";

  @ConfigObject private Messages messages = new Messages();

  @Comment("bar")
  private String bar = "baz";

  @Comment("this is a list")
  private List<String> list = Arrays.asList("Hello", "bla bla");

  @Comment("baz")
  private int a = 1;

  @Comment("All supported messages")
  public static class Messages {

    // comments in sections are not supported

    @Key("no-console")
    private String noConsole = "No console!";

    @Key("console-only")
    private String consoleOnly = "This command is console only!";

    public String getNoConsole() {
      return noConsole;
    }

    public String getConsoleOnly() {
      return consoleOnly;
    }
  }

  @ConfigObject private Location location = new Location();

  @Comment("The location of the player")
  public static class Location {

    private String world = "world";

    private int x = 20;
    private int y = 2;
    private int z = 1;
  }

  @Comment("Second location")
  private LocationNoConfigObject locationTwo = new LocationNoConfigObject("world", 20, 2, 1);

  @Comment("Third location")
  @Key("location-no-three")
  private LocationNoConfigObject locationThree =
      new LocationNoConfigObject("world_the_end", 200, 22, 333);

  @ConfigObject
  @Key("new-section")
  private NonExistingSection nonExistingSection = new NonExistingSection();

  @Comment("This is some dummy section")
  public static class NonExistingSection {
    private String foo = "foo";
    private int bar = 2;
    private double baz = 2.0;
    private boolean enabled = true;
  }

  public String getName() {
    return name;
  }

  public String getFoo() {
    return foo;
  }

  public Messages getMessages() {
    return messages;
  }

  public String getBar() {
    return bar;
  }

  public List<String> getList() {
    return list;
  }

  public int getA() {
    return a;
  }

  public NonExistingSection getNonExistingSection() {
    return nonExistingSection;
  }

  public Location getLocation() {
    return location;
  }

  public LocationNoConfigObject getLocationTwo() {
    return locationTwo;
  }
}
