package com.mrivanplays.annotationconfig.yaml;

import com.mrivanplays.annotationconfig.core.annotations.ConfigObject;
import com.mrivanplays.annotationconfig.core.annotations.Key;
import com.mrivanplays.annotationconfig.core.annotations.comment.Comment;
import java.util.Arrays;
import java.util.List;

@Comment("Generated by AnnotationConfig v2.0.0")
public class YAMLTestSubject {

  @Comment("name")
  @Key("custom-name")
  private String name = "Ivan";

  @Comment("foo")
  private String foo = "bar";

  @ConfigObject private Messages messages = new Messages();

  @Comment("bar")
  private String bar = "baz";

  @Comment("this is a list")
  private List<String> list = Arrays.asList("Hello", "bla bla");

  @Comment("All supported messages")
  public static class Messages {

    // comments in sections are not supported

    @Key("no-console")
    private String noConsole = "No console!";

    @Key("console-only")
    private String consoleOnly = "This command is console only!";

    public String getNoConsole() {
      return noConsole;
    }

    public String getConsoleOnly() {
      return consoleOnly;
    }
  }

  @ConfigObject private Location location = new Location();

  @Comment("The location of the player")
  public static class Location {

    private String world = "world";

    private int x = 20;
    private int y = 2;
    private int z = 1;
  }

  @Comment("Second location")
  private LocationNoConfigObject locationTwo = new LocationNoConfigObject("world", 20, 2, 1);

  public String getName() {
    return name;
  }

  public String getFoo() {
    return foo;
  }

  public Messages getMessages() {
    return messages;
  }

  public String getBar() {
    return bar;
  }

  public List<String> getList() {
    return list;
  }

  public Location getLocation() {
    return location;
  }

  public LocationNoConfigObject getLocationTwo() {
    return locationTwo;
  }
}
