package com.mrivanplays.annotationconfig.toml;

import java.io.StringWriter;
import java.util.Arrays;
import java.util.stream.Collectors;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class TestTOML {

  @Test
  public void testLoad() {
    TOMLTestSubject config = new TOMLTestSubject();
    TomlConfig.getConfigResolver()
        .load(config, getClass().getClassLoader().getResourceAsStream("test-toml.toml"));

    Assertions.assertEquals(25577, config.getServer().getPort());
  }

  @Test
  public void testDump() {
    TOMLTestSubject config = new TOMLTestSubject();
    StringWriter writer = new StringWriter();

    TomlConfig.getConfigResolver().dump(config, writer);

    String expected =
        "# Generated by AnnotationConfig v2.0.0\n"
            + "\n"
            + "# name\n"
            + "name = 'Ivan'\n"
            + "\n"
            + "# bar\n"
            + "bar = false\n"
            + "\n"
            + "# Server\n"
            + "server.ip = 'localhost'\n"
            + "server.theport = 25565\n"
            + "\n"
            + "# OffsetDateTime\n"
            + "\n"
            + "# This has been dumped with the default serializer\n"
            + "default-serializer.foo = 'foo string'\n"
            + "default-serializer.bar = 1\n"
            + "default-serializer.baz = 0.555";

    // remove date and dateTime fields since we can't get exact expected time
    String received =
        Arrays.stream(writer.toString().split("\n"))
            .filter(l -> !l.startsWith("date"))
            .filter(l -> !l.startsWith("dateTime"))
            .collect(Collectors.joining("\n"));

    Assertions.assertEquals(expected, received);
  }
}
